### ISSUE TITLE
Can you wait for a zab::async_function<> to finish?

### ISSUE THREAD

**Issue by chenscottus** [Donald-Rupin/zab#15]
How can wait for the zab::async_function<> your_class::foo(); to finish after run it?

Thanks,

**Comment by Donald-Rupin** [comment]
Its is not possible to wait for a `zab::async_function<>` function to finish. You could thing of this coroutine as dispatch and detach.

You could use as `zab::simple_promise<>` (awaitable but with no return type).

```c++
zab::simple_promise<> bar();

// dispatch and detach
zab::async_function<> foo()
{
   // Wait until it finishes
   co_await bar();

}
```
