### ISSUE TITLE
How can you run `zab::simple_future<bool>` in the background and get the result later?

### ISSUE THREAD

**Issue by chenscottus** [Donald-Rupin/zab#16]
How can run asyn zab::simple_future<bool> your_class::bar();?
like that:
  run it
  do some other stuff
  after than, wait for it to finish

**Comment by Donald-Rupin** [comment]
The API was not really designed to push background tasks and get the result later. I might add something so its possible to achieve this easily in the future. It is possible now using `zab::wait_for(...);`

If you wanted to do:
```
start work A

do work B

get result from A
``` 

You could achieve it with:
```
zab::simple_future<bool> work_A();

zab::simple_future<> work_B();

zab::async_function<> foo() 
{
   // Run in parallel
   auto[a_result, _ ] = zab::wait_for(work_A(), work_B());

}

```
